### ISSUE TITLE
move border to box-model

### ISSUE THREAD

**Issue by dmitriyK1** [constverum/stylelint-config-rational-order#3]
I suggest moving border property into box-model section because where it belongs

**Comment by constverum** [comment]
Hey @dmitriyK1! Try to update the package and change your config like below:
```js
{
  "extends": [
    "stylelint-config-rational-order/borderInBoxModel"
  ]
}
```

**Comment by dmitriyK1** [comment]
@constverum Thanks this will come handy!

**Comment by constverum** [comment]
From now on (v.0.1.0+) please use the plugin option to get this behavior.
```
  "plugins": [
    "stylelint-config-rational-order/plugin"
  ],
  "rules": {
    "plugin/rational-order": [true, {
      "border-in-box-model": true,
    }]
  }
```

`stylelint-config-rational-order/borderInBoxModel` still works, but was deprecated and will be removed in the future.
