### ISSUE TITLE
Missing few important proprieties 

### ISSUE THREAD

**Issue by mrleblanc101** [constverum/stylelint-config-rational-order#8]
Hi,
The preset is missing the `content` css propriety for pseudo-elements.
The preset is missing the `mix-blend-mode` and `isolation` for photoshop-like layer effects
The preset is missing the `object-fit` propriety for image positioning/sizing

**Comment by mrleblanc101** [comment]
`content` should be right before `display` in box-model.
`mix-blend-mode` and `isolation` should either go after `background-blend-mode` in display or somewhere in `misc`

**Comment by theKashey** [comment]
+ `grid-*` properties. It's more about - it's good to have `grid-column-start` before `grid-column-end`

**Comment by constverum** [comment]
Done, thanks!
All these changes available in v0.1.1
