### ISSUE TITLE
Why I should use rational order?

### ISSUE THREAD

**Issue by theKashey** [constverum/stylelint-config-rational-order#9]
There is no answer to this question, and still, many devs live with alphabetical sort, and seeing no drawbacks of using it.

It would be good to point add some articles here:
- https://webdesign.tutsplus.com/articles/outside-in-ordering-css-properties-by-importance--cms-21685 - "Outside-in" principle
- https://dev.to/thekashey/happy-potter-and-the-order-of-css-5ec - my compilation of reasons to use grouping.

**Comment by constverum** [comment]
It's definitely a reasonable idea, thanks, Anton! Added to the FAQ.
And thanks for mentioning the project in your post! =)
